sbatch jobs/jobdescription-mnist_conv_128_2.sh
sbatch jobs/jobdescription-mnist_conv_128_4.sh
sbatch jobs/jobdescription-mnist_conv_128_8.sh
sbatch jobs/jobdescription-mnist_conv_256_2.sh
sbatch jobs/jobdescription-mnist_conv_256_4.sh
sbatch jobs/jobdescription-mnist_conv_256_8.sh
sbatch jobs/jobdescription-mnist_conv_512_2.sh
sbatch jobs/jobdescription-mnist_conv_512_4.sh
sbatch jobs/jobdescription-mnist_conv_512_8.sh
sbatch jobs/jobdescription-mnist_non-conv_128_2.sh
sbatch jobs/jobdescription-mnist_non-conv_128_4.sh
sbatch jobs/jobdescription-mnist_non-conv_128_8.sh
sbatch jobs/jobdescription-mnist_non-conv_256_2.sh
sbatch jobs/jobdescription-mnist_non-conv_256_4.sh
sbatch jobs/jobdescription-mnist_non-conv_256_8.sh
sbatch jobs/jobdescription-mnist_non-conv_512_2.sh
sbatch jobs/jobdescription-mnist_non-conv_512_4.sh
sbatch jobs/jobdescription-mnist_non-conv_512_8.sh
sbatch jobs/jobdescription-fashion-mnist_conv_128_2.sh
sbatch jobs/jobdescription-fashion-mnist_conv_128_4.sh
sbatch jobs/jobdescription-fashion-mnist_conv_128_8.sh
sbatch jobs/jobdescription-fashion-mnist_conv_256_2.sh
sbatch jobs/jobdescription-fashion-mnist_conv_256_4.sh
sbatch jobs/jobdescription-fashion-mnist_conv_256_8.sh
sbatch jobs/jobdescription-fashion-mnist_conv_512_2.sh
sbatch jobs/jobdescription-fashion-mnist_conv_512_4.sh
sbatch jobs/jobdescription-fashion-mnist_conv_512_8.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_128_2.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_128_4.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_128_8.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_256_2.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_256_4.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_256_8.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_512_2.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_512_4.sh
sbatch jobs/jobdescription-fashion-mnist_non-conv_512_8.sh
