sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_128,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_128,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_128,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_256,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_256,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_256,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_512,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_512,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_512,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_128,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_128,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_128,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_256,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_256,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_256,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_512,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_512,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_512,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_128,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_128,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_128,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_256,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_256,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_256,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_512,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_512,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"convolutional",_"embedding-dimension":_512,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_128,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_128,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_128,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_256,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_256,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_256,_"num-heads":_8}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_512,_"num-heads":_2}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_512,_"num-heads":_4}.sh
sbatch jobs/jobdescription-{"dataset":_"fashion-mnist",_"image-embedding":_"non-convolutional",_"embedding-dimension":_512,_"num-heads":_8}.sh
