sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 128, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 128, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 128, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 256, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 256, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 256, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 512, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 512, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "convolutional", "embedding-dimension": 512, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 128, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 128, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 128, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 256, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 256, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 256, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 512, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 512, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "mnist", "image-embedding": "non-convolutional", "embedding-dimension": 512, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 128, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 128, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 128, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 256, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 256, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 256, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 512, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 512, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "convolutional", "embedding-dimension": 512, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 128, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 128, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 128, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 256, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 256, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 256, "num-heads": 8}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 512, "num-heads": 2}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 512, "num-heads": 4}.sh
sbatch jobs/jobdescription-{"dataset": "fashion-mnist", "image-embedding": "non-convolutional", "embedding-dimension": 512, "num-heads": 8}.sh
